name: Update Languages Animation
on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate languages animation
        uses: JasonEtco/generate-linguist-animation@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: "assets/languages.svg"

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/
          git commit -m "Update languages animation [skip ci]" || echo "No changes"
          git push
